# Generated by Django 6.0.1 on 2026-02-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
