# Generated by Django 6.0.1 on 2026-02-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_purchase_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные при получении'), ('card', 'Картой при получении')], default='cash', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
