# Generated by Django 6.0.1 on 2026-02-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз (бесплатно)'), ('krasnoyarsk', 'Доставка по Красноярску (400 ₽)'), ('russia', 'Доставка по России и миру')], default='pickup', max_length=15, verbose_name='Способ доставки'),
        ),
    ]
