# Generated by Django 6.0.1 on 2026-02-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_purchase_delivery_cost_purchase_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('created', '🟡 Создан'), ('assembled', '🟠 Собран'), ('shipped', '🔵 Доставляется'), ('delivered', '🟢 Доставлен'), ('cancelled', '🔴 Отменен')], default='created', max_length=15, verbose_name='Статус заказа'),
        ),
    ]
