# Generated by Django 6.0.1 on 2026-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданных копий'),
        ),
    ]
