# Generated by Django 6.0.1 on 2026-02-10 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_sold_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='confirmed_by_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_confirmed_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил курьер'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='confirmed_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_confirmed_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил сотрудник'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='courier_confirmed_delivery',
            field=models.BooleanField(default=False, verbose_name='Подтверждено курьером для доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='courier_confirmed_shipping',
            field=models.BooleanField(default=False, verbose_name='Подтверждено курьером для отправки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='staff_confirmed_delivery',
            field=models.BooleanField(default=False, verbose_name='Подтверждено продавцом для доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='staff_confirmed_shipping',
            field=models.BooleanField(default=False, verbose_name='Подтверждено продавцом для отправки'),
        ),
    ]
