# Generated by Django 6.0.1 on 2026-02-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_purchase_confirmation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='condition',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Состояние при получении от магазина'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='condition_delivered',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Состояние при доставке'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='courier_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии курьера при получении'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_notes_courier',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии курьера'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_notes_staff',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии продавца'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кто получил заказ'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя получившего'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='courier_confirmed_delivery',
            field=models.BooleanField(default=False, verbose_name='Курьер подтвердил доставку клиенту'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='courier_confirmed_shipping',
            field=models.BooleanField(default=False, verbose_name='Курьер подтвердил получение для доставки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='staff_confirmed_delivery',
            field=models.BooleanField(default=False, verbose_name='Продавец подтвердил доставку'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='staff_confirmed_shipping',
            field=models.BooleanField(default=False, verbose_name='Продавец подтвердил готовность к отправке'),
        ),
    ]
