# Generated by Django 6.0.1 on 2026-02-11 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_purchase_condition_purchase_condition_delivered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='condition_delivered',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='courier_notes',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_notes_courier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_notes_staff',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='recipient',
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к доставке'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код выдачи'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='confirmed_by_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_delivery_courier', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил доставку (курьер)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='confirmed_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_shipping_staff', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил сборку (сотрудник)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='courier_confirmed_delivery',
            field=models.BooleanField(default=False, verbose_name='Подтверждена доставка (курьером)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='courier_confirmed_shipping',
            field=models.BooleanField(default=False, verbose_name='Подтвержден прием (курьером)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='staff_confirmed_delivery',
            field=models.BooleanField(default=False, verbose_name='Подтверждена доставка (сотрудником)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='staff_confirmed_shipping',
            field=models.BooleanField(default=False, verbose_name='Подтверждена сборка (сотрудником)'),
        ),
    ]
